name = "Yeastdonkey's Modpack (client)"
author = "Yeastdonkey"
version = "1.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66f9a23a7f0c88d7f177ffe0d02bb086d1372a96d5a2b73bd211bbdb40795e19"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
