name = "Yeastdonkey's Modpack"
author = "Yeastdonkey"
version = "1.3.2c"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "045b71d08b99fd9e69f7ebcf116f82fcdfd1afa872f9fd7eeb3ce5071d507e41"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
